num1=int(input("Enter First No :"))
num2=int(input("Enter Second No :"))
print("Addition :",num1+num2)
print("Subtraction :",num1-num2)
print("Multiplication :",num1*num2)
print("Division :",num1/num2)
